sudo: required
services:
  - docker

before_install:
  - docker build -t williamjieh/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run williamjieh/react-test npm run test -- --coverage

after_success:
  - docker build -t williamjieh/multi-client ./client
  - docker build -t williamjieh/multi-nginx ./nginx
  - docker build -t williamjieh/multi-server ./server
  - docker build -t williamjieh/multi-worker ./worker
  # Log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push williamjieh/multi-client 
  - docker push williamjieh/multi-nginx
  - docker push williamjieh/multi-server
  - docker push williamjieh/multi-worker